services:
  micro_ros_agent:
    image: microros/micro-ros-agent:${ROS_DISTRO}
    privileged: true
    tty: true
    volumes:
      - /dev:/dev
    command: ["serial", "-b", "${BAUDRATE}", "--dev", "${PORT}"]
